# Generated by Django 3.2 on 2021-04-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0002_alter_productcategory_options'),
        ('eshop_products', '0002_auto_20210417_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshop_products_category.ProductCategory', verbose_name='دسته بندی ها'),
        ),
    ]
