# Generated by Django 3.2 on 2021-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده / نشده'),
        ),
    ]
